spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/marketdb
    username: postgres
    password: root
    hikari:
      schema: production
  jpa:
    show-sql: true